### PR TITLE
linters.yml added on .github folder and also .gitignore

### PR DESCRIPTION
**Pull request by Nkaleth**
In this project, we learned to:

- Create branches with different base branches.
- Understand the concept of version control.
- Follow GitHub flow.
- Open pull requests in GitHub.
- Write descriptive, easy-to-understand commit messages.
- Write short, detailed, easy-to-understand descriptions of pull requests.
- Write a descriptive and easy-to-understand README in business English for every project submitted.
- Demonstrate an ability to submit a project for code review.

### CODE REVIEW

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @Nkaleth, 

Good job so far!
You did it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors 💯  
- Correct Github flow ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- - [x] Kindly **all main headers** from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo. The only optional section is FAQ.
- [x] Please 🙏🏽 remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
  - Kindly writhe a descriptive title and list the activities in your pull request 👇🏽 

| Your PR | Expected PR |
|---|---|
| image | image |

- [x] **[OPTIONAL]** Kindly use a descriptive name for your feature branch, for example, `hello-microverse`.

- [x] **[OPTIONAL]** Please 🙏🏽 delete the file that you are not using in your repo.

image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nkaleth** [comment]
@franclobo About the first suggestion. I don't understand what are the main headers of the README template. Do you have an example of the correct README for this little project? 
For example, I don't know how to complete these required sections:   
- Live Demo
- Getting Started
It's a little bit confusing to complete all the README considering that it is only an HTML/CSS project. Thanks in advance for your help.

**Comment by franclobo** [comment]
Hello, @Nkaleth 
Thanks for reaching out to me, the idea of the README file is to communicate with the user, in this case for the LIVE DEMO you could write "We are working on that" and for the GETTING STARED describe the steps for a common user should follow to open your project: 👇🏽 
- Clone this [repo](git@github.com:Nkaleth/Hello-Microverse.git)
- Go to the `feature-a` branch.
- Open the index.html file in your browser
- Enjoy it. 😃

**Review by BregornOriginal — APPROVED** [review]
## Hi @Nkaleth 📗 📗 📗 
## Your project is complete!  There is nothing else to say other than... it's time to merge it 👏🏼 👏🏼 👏🏼 

## Congratulations! 🥳 🥳 🥳 

## Highlights

✅ Requeriments accomplished 🥇 
✅ Your README now looks professional 💯 

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

## - [OPTIONAL] **From now on remember to use meaningful commits. Instead of `Added` you have to say `Add`**



Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

**Comment by Nkaleth** [comment]
@BregornOriginal Thanks for the review. Do you mean: 
Instead: "Html.index file added" I have to write: "Add Html.index file"? In the commits? That sound a little bit confusing to me.

**Pull request merged**
